# docker-compose.yml
version: '3.8'

services:
  build:
    build:
      context: ..
      dockerfile: docker/Dockerfile.Build
    volumes:
      - ./dist:/output

  lxmfy-bot:
    build: .
    volumes:
      - ./.reticulum:/root/.reticulum
      - ./config:/bot/config
    command: ["lxmfy", "run", "echo"]
